version: 2
jobs:
  install:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
  build:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn build
  e2e:
    docker:
      - image: circleci/node:dubnium-browsers
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_DB: psqluer
          POSTGRES_USER: psqluer
          POSTGRES_PASSWORD: psqlpassword
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: 
          command: yarn e2e
          environment:
            DATABASE_URL: postgres://psqluer:psqlpassword@localhost:5432/psqluer
            JWT_SECRET: aaaa
            API_PORT: 3000
            API_HOST: localhost
            API_PROTOCOL: http
  
workflows:
  version: 2
  build-and-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - e2e:
          requires:
            - build
